theme: jekyll-theme-slate
title: CS109A Final Project
description: Machine Learning & Analysis for Twitter Bot Detection
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
