theme: jekyll-theme-slate
title: CS109A FinalProject-Group68
description: Detecting walking and running slopes using IMUS
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
